### ISSUE TITLE
contrast experiment

### ISSUE THREAD

**Issue by huawang123** [weihao94/BUSU-Net#1]
Compared to S-Unet？ too similar...

**Comment by weihao94** [comment]
@huawang123 Are you referring to this https://ieeexplore.ieee.org/abstract/document/8842560 ? If it is, I did not compare to this as it did not pop up during my exhaustive search of related work online. Apologies for that, will include it for comparison in my next work. Actually, there are differences, namely that BUSU-Net contains a cascading architecture of U-Nets of unequal depths, rather than those with same depths like in S-Unet. Furthermore, S-Unet does not consider cases of cascading like BUSUSUBU...BUSU, BUSUBUSU...BUSU, i.e. 'rotations' or 'inversions' in order of the cascading/ensemble components. Hope that helps, and apologies again for missing out on S-Net's comparison.

**Comment by huawang123** [comment]
Since this is also an ensemble approach and was also tested on the DRIVE dataset, is it worth comparing? What's more, it has been published before you sent it, so I think it is necessary to compare it. How to show the superiority of your model.

**Comment by weihao94** [comment]
@huawang123 Thanks for your feedback, yes I agree, though it is not representative of the S-net. I can only compare with Mi-unet, as my experimental results only allow one unit of ensemble as a basis for comparison. I am not able to compare with S-net with multiple units of  Mi-unet as currently I do not have access to the computing power required to make such comparisons. Will that be alright?

I'll push a version update with Mi-unet results cited soon.

**Comment by huawang123** [comment]
OK! If there is an opportunity to  exchange and cooperate, look forward to!

**Comment by weihao94** [comment]
@huawang123 Thanks, that will be great! I've made a submission for a revision of the manuscript, for inclusion of S-UNet's Mi-UNet's results, citation and discussion. It is scheduled to be announced at Tue, 10 Mar 2020 00:00:00 GMT.
